name: amqpcat
base: core18
version: git
summary: CLI tool for publishing to and consuming from AMQP servers
description: |
  netcat for AMQP. A CLI tool for publishing to and consuming from
  AMQP servers.
license: MIT

grade: stable
confinement: strict

apps:
  amqpcat:
    command: amqpcat
    plugs:
      - network

parts:
  amqpcat:
    plugin: crystal
    crystal-build-options:
      - --release
    source: https://github.com/cloudamqp/amqpcat.git
    build-packages:
      - git
      - libssl-dev
      - libevent-dev
    override-build: |
      snapcraftctl build
      strip $SNAPCRAFT_PART_INSTALL/bin/*
